//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriHesabi
    {
        public int islemNo { get; set; }
        public string sonHesap { get; set; }
        public string girisTarihi { get; set; }
        public string cikisTarihi { get; set; }
        public Nullable<int> kisiSayisi { get; set; }
        public Nullable<int> odaNo { get; set; }
        public Nullable<int> musteriNo { get; set; }
    
        public virtual MusteriKayit MusteriKayit { get; set; }
        public virtual Odalar Odalar { get; set; }
    }
}
