//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Odalar()
        {
            this.MusteriHesabis = new HashSet<MusteriHesabi>();
        }
    
        public int odaNo { get; set; }
        public Nullable<decimal> odaFiyat { get; set; }
        public Nullable<int> yatakSayisi { get; set; }
        public string odaTuru { get; set; }
        public Nullable<int> servisNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusteriHesabi> MusteriHesabis { get; set; }
        public virtual Servisler Servisler { get; set; }
    }
}
